# Generated by Django 2.1.5 on 2019-10-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='SAY SOMETHIG', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='your title', max_length=255),
        ),
    ]
